-- CreateEnum
CREATE TYPE "InitiativeType" AS ENUM ('WORK_BASED_LEARNING', 'CURRICULUM_INNOVATION', 'PARTNERSHIP', 'MOBILITY', 'INTERNATIONAL_TRAINING_ACTIVITIES', 'OTHER');

-- AlterTable
ALTER TABLE "RepositoryInitiative" ADD COLUMN     "initiativeType" "InitiativeType" NOT NULL DEFAULT 'PARTNERSHIP';
